version: '3.3'
services:
  mysql-db:
    container_name: mysql-db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'flask_authentication'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    networks:
      - backend

  flask-app:
    container_name: flask-app
    build: .
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - mysql-db


networks:
  backend: